services:
  postgres:
    profiles:
      - 'backing-service'
      - 'all'
      - 'dev'
      - 'api'
    image: postgres:16.4-alpine
    container_name: square_me_microservices_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    profiles:
      - backing-service
    image: mailhog/mailhog:latest
    platform: linux/amd64
    container_name: square_me_mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MH_STORAGE: memory

  rabbitmq:
    profiles:
      - backing-service
    image: rabbitmq:3-management
    platform: linux/amd64
    container_name: square_me_rabbitmq
    restart: always
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    profiles:
      - 'backing-service'
      - 'all'
      - 'dev'
      - 'api'
    container_name: square_me_microservices_redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass mypassword --port 6379 --databases 16
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
