services:
  postgres:
    profiles:
      - 'backing-service'
      - 'all'
      - 'dev'
      - 'api'
    image: postgres:16.4-alpine
    container_name: square_me_microservices_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    profiles:
      - backing-service
    image: mailhog/mailhog:latest
    platform: linux/amd64
    container_name: square_me_mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MH_STORAGE: memory

  rabbitmq:
    profiles:
      - backing-service
    image: rabbitmq:3-management
    platform: linux/amd64
    container_name: square_me_rabbitmq
    restart: always
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    profiles:
      - 'backing-service'
      - 'all'
      - 'dev'
      - 'api'
    container_name: square_me_microservices_redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass mypassword --port 6379 --databases 16
    volumes:
      - redis_data:/data

  auth:
    profiles:
      - 'all'
      - 'api'
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    container_name: square_me_auth
    ports:
      - '3000:3000'
      - '3333:3333'
    environment:
      PORT: 3000
      SWAGGER_PATH: 'swagger'
      SWAGGER_TITLE: 'Auth Service'
      SWAGGER_DESCRIPTION: 'Manages user and authentication'
      CORS_ORIGINS: transaction:3001
      JWT_SECRET: TDCYJMDvpGdL+t5qn8nKSQ2NGAM6UL9+QnPy87Ehrlw=
      JWT_EXPIRATION_MS: 28800000
      AUTH_GRPC_SERVICE_URL: auth:3333
      WALLET_GRPC_SERVICE_URL: wallet:7777
      INTEGRATION_GRPC_URL: integration:4444
      SERVICE_ENTITY_PREFIX: 'auth-service-'
      DATABASE_URL: postgres://postgres:example@postgres:5432/auth?schema=public

  integration:
    profiles:
      - 'all'
      - 'api'
    build:
      context: .
      dockerfile: ./apps/integration/Dockerfile
    container_name: square_me_integration
    ports:
      - '4444:4444'
    environment:
      PORT: 4444
      EXCHANGE_RATE_API_KEY: '<Insert Key here>'
      EXCHANGE_RATE_URL: 'https://v6.exchangerate-api.com'
      WALLET_GRPC_SERVICE_URL: integration:4444
      INTEGRATION_GRPC_URL: integration:4444
      SERVICE_ENTITY_PREFIX: 'auth-service-'
      REDIS_URL: redis://:mypassword@redis:6379/0
    env_file: ./apps/integration/docker.env

  notification:
    profiles:
      - 'all'
      - 'api'
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    container_name: square_me_notification
    ports:
      - '5555:5555'
    environment:
      PORT: 5555
      RABBIT_MQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBIT_MQ_QUEUE_NAME: email-queue
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_FROM: 'Square Me <help@square-me.com>'

  transaction:
    profiles:
      - 'all'
      - 'api'
    build:
      context: .
      dockerfile: ./apps/transaction/Dockerfile
    container_name: square_me_transaction
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      SWAGGER_PATH: swagger
      SWAGGER_TITLE: 'Transaction Service'
      SWAGGER_DESCRIPTION: 'Orchestrates creation of order, debiting of wallet and sending notification'
      CORS_ORIGINS: auth:3333
      WALLET_GRPC_SERVICE_URL: wallet:7777
      AUTH_GRPC_SERVICE_URL: auth:3333
      INTEGRATION_GRPC_URL: integration:4444
      DATABASE_URL: postgres://postgres:example@postgres:5432/transaction?schema=public
      SERVICE_ENTITY_PREFIX: transaction-service-
      REDIS_URL: redis://:mypassword@redis:6379/0
      RABBIT_MQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBIT_MQ_QUEUE_NAME: email-queue

  wallet:
    profiles:
      - 'all'
      - 'api'
    build:
      context: .
      dockerfile: ./apps/wallet/Dockerfile
    container_name: square_me_wallet
    ports:
      - '7777:7777'
    environment:
      PORT: 7777
      DATABASE_URL: postgres://postgres:example@postgres:5432/wallet?schema=public
      WALLET_GRPC_SERVICE_URL: wallet:7777
      INTEGRATION_GRPC_URL: integration:4444
      SERVICE_ENTITY_PREFIX: wallet-service-

volumes:
  postgres_data:
  redis_data:
